---
# =============================================================================
# Defaults - stepca_install v1.2
# Versions verifiees fonctionnelles le 2026-06-20
# =============================================================================

# Format paquet : step-cli_X.Y.Z-1_amd64.deb (suffixe -1 obligatoire depuis 0.27.x)
step_version: "0.29.0"
step_ca_version: "0.29.0"

step_arch_map:
  x86_64: amd64
  aarch64: arm64
