---
- name: "Phase 1 - Installation et initialisation step-ca sur lb-01"
  hosts: stepca
  become: true
  gather_facts: true

  pre_tasks:
    - name: "Attendre la connectivite SSH"
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 120

  roles:
    - stepca_install
    - stepca_init
