---
- name: "Deploiement OpenLDAP (ldap-01)"
  hosts: ldap
  become: true
  gather_facts: true

  pre_tasks:
    - name: "Attendre la connectivite SSH"
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 120

  roles:
    - openldap
