---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart redis
  ansible.builtin.systemd:
    name: redis-server
    state: restarted

- name: restart netbox
  ansible.builtin.systemd:
    name: netbox
    state: restarted

- name: restart netbox-rq
  ansible.builtin.systemd:
    name: netbox-rq
    state: restarted

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
